name: "Hello"

on:
  workflow_dispatch:

jobs: 
  printyourname:
    runs-on: [self-hosted]
    steps:
      - uses: @actions/checkout@v1
      - uses: ./
        with:
          name: "Kajal"
          greet: "Hello greet"